email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "/home/ubuntu/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current"
        GENCAT_ETL = "/var/www/gobierto-etl-gencat/current"
        STORAGE_DIR = "${GENCAT_ETL}/tmp"
        LAYOUT_LOCATION = "http://governobert.gencat.cat/templates?mode=html&code=GOOB0001"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO = "/var/www/gobierto/current"
        // GENCAT_SITE_DOMAIN = "gencat.gobierto.es"
    }
    stages {
        stage('Extract > Download layout') {
            steps {
               sh "wget -O ${STORAGE_DIR}/layouts_application.html '${LAYOUT_LOCATION}'"
            }
        }
        stage('Transform > Add custom tags to layout') {
            steps {
                sh "cd ${GENCAT_ETL}; ruby operations/import_custom_layout/generate_template.rb ${STORAGE_DIR}/layouts_application.html ${STORAGE_DIR}/layouts_application.html.erb"
            }
        }
        stage('Load > Save as site template') {
            steps {
                sh "cd ${GOBIERTO}; bin/rails runner ${GENCAT_ETL}/operations/import_custom_layout/load_template.rb ${GENCAT_SITE_DOMAIN} ${STORAGE_DIR}/layouts_application.html.erb"
            }
        }
    }
    // post {
    //     failure {
    //         echo 'This will run only if failed'
    //         mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
    //             charset: 'UTF-8',
    //             subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
    //             to: email
    //     }
    // }
}
