email = "popu-servers+jenkins@populate.tools"
pipeline {
    agent any
    environment {
        PATH = "$HOME/.rbenv/shims:$PATH"
        GENCAT_ETL = "/var/www/gobierto-etl-gencat/current"
        STORAGE_DIR = "/var/lib/jenkins/jobs/gobierto-etl-gencat\\ layout/builds/${env.BUILD_NUMBER}"
        LAYOUT_LOCATION = "https://governobert.gencat.cat/templates?mode=html&code=GOOB0001"
        LOCALES = "ca es"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO = "/var/www/gobierto/current"
        // GENCAT_SITE_DOMAIN = "gencat.gobierto.es"
    }
    stages {
        stage('Extract > Download layout') {
            steps {
                sh "cd ${GENCAT_ETL}; ruby operations/import_custom_layout/download_layout.rb ${STORAGE_DIR} '${LAYOUT_LOCATION}' ${LOCALES}"
            }
        }
        stage('Transform > Add custom tags to layout') {
            steps {
                sh "cd ${GENCAT_ETL}; ruby operations/import_custom_layout/generate_template.rb ${STORAGE_DIR}/downloaded_layout_es.html ${STORAGE_DIR}/layouts_application_es.html.erb"
                sh "cd ${GENCAT_ETL}; ruby operations/import_custom_layout/generate_template.rb ${STORAGE_DIR}/downloaded_layout_ca.html ${STORAGE_DIR}/layouts_application_ca.html.erb"
            }
        }
        stage('Transform > Merge templates') {
            steps {
                sh "cd ${GENCAT_ETL}; ruby operations/import_custom_layout/merge_templates.rb ${STORAGE_DIR} ${LOCALES}"
            }
        }
        stage('Load > Save as site template') {
            steps {
                sh "cd ${GOBIERTO}; bin/rails runner ${GENCAT_ETL}/operations/import_custom_layout/load_template.rb ${GENCAT_SITE_DOMAIN} ${STORAGE_DIR}/layouts_application.html.erb"
            }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email
        }
    }
}
